### ISSUE TITLE
I liked your video and thought I'd ask how to use the plugin

### ISSUE THREAD

**Issue by whoamigo** [kursad-k/blender-kasmas#1]
Just in case you're watching the repository, I thought I'd ask how to install and use your plugin. Is everything (colours, material, texture map) procedural?

Thank you for any instructions on how to use it in Blender 3.0.

**Comment by kursad-k** [comment]
Hi,

This is procedural as in it requires two positions for a muscle to be added on the geometry, it needs  two insertion positions for a muscle mass to be created.

**Comment by whoamigo** [comment]
@kursad-k thank you very much for your fast response. I really was hoping you were watching this repository. A minute ago, I was browsing your art on your  Web site. You're really gifted 🥇.

@kursad-k please, can you give me instructions one how to use the __init__.py as a plugin. I tried putting it in a zip archive and it installs on Blender 3.0 without problems.

Now in Object mode, I do see a Misc tab that shows a KasMas Tools drop down when clicked but nothing else happens. Can you please shed some light on were to go from there to get it to add geometry (shortcuts, etc.).

Thanks 👍

**Comment by kursad-k** [comment]
Have you tried it with 2.80 or 2.90? There might be some API changed in the most recent versions that breaks the functionality. I will give it a try soon.
